CREATE DATABASE GFG_SIH_EMR;
USE GFG_SIH_EMR;

/*PATIENT REGISTRATION DETAILS*/
CREATE TABLE PATIENT_DETAILS(
	PATIENT_NAME VARCHAR(200),GENDER VARCHAR(12),
	UID VARCHAR(12) PRIMARY KEY,
	DOB DATE, ALLERGIES VARCHAR(1000),
    PHONE VARCHAR(10),
    CURR_MEDICATION VARCHAR(200), SURGERIES VARCHAR(1000),
    IMMUNIZATION VARCHAR(1000)
);
DROP TABLE PATIENT_DETAILS;

/*DOCTOR REGISTRATION*/
CREATE TABLE DOCTOR_DETAILS(
	DOCTOR_NAME VARCHAR(200), SPECIALITY VARCHAR(20),
    PHONE_NO VARCHAR(10), EMAIL_ID VARCHAR(320), LICENSE_NO VARCHAR(25) UNIQUE,
    DOC_PASS BINARY(60), DOCID VARCHAR(8) PRIMARY KEY
);
DROP TABLE DOCTOR_DETAILS;

/*DOCTOR=>PATIENTS*/
CREATE TABLE DOCS_PATS(APPID INT PRIMARY KEY AUTO_INCREMENT,DID VARCHAR(12), PID VARCHAR(12),TOKEN INT,
				FOREIGN KEY (DID) REFERENCES DOCTOR_DETAILS(DOCID) ON DELETE CASCADE ON UPDATE CASCADE, 
                FOREIGN KEY (PID) REFERENCES PATIENT_DETAILS(UID) ON DELETE CASCADE ON UPDATE CASCADE
);
DROP TABLE DOCS_PATS;